### ISSUE TITLE
GitHub pages not liking "whiteboard" as theme in _config.yml

### ISSUE THREAD

**Issue by colinmathews** [mpociot/whiteboard#19]
Love this project, nice work.

I'm using GitHub pages on my repo so that my documentation is easily hosted/updated. Every time I push to master and it builds, it sends me the warning below via email. Everything still works, but that warning is super annoying. 

The problem is this line of my [`_config.yml` file](https://github.com/colinmathews/mailshake-api-docs/blob/ad4268128e5ddf14fb600b3b9fbf58f5357e3531/_config.yml#L30).

Any ideas?

> The page build completed successfully, but returned the following warning for the `master` branch:
> 
> You are attempting to use a Jekyll theme, "whiteboard", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

**Comment by psigen** [comment]
@colinmathews: I'm not the maintainer, but I think I might know what this is.

[By default, GitHub Pages will try to build your repository using **Jeykll**, another static site generator.](https://help.github.com/articles/about-github-pages-and-jekyll/) It detects this by looking for Jekyll config files in your repo.  Confusingly, Jeykll _also_ uses a file called `_config.yml` in the root of your directory for its configuration.

I think you are getting this message because GitHub Pages is trying to use your _whiteboard_ configuration with _Jekyll_.

You can prevent this behavior by [adding a `.nojekyll` file to the root of your repo.](https://github.com/blog/572-bypassing-jekyll-on-github-pages)

**Comment by colinmathews** [comment]
@psigen Ah! Thank you so much, that worked perfectly.
